model:
  env:
    MODEL_PORT: '5000'
  image:
    pullPolicy: Always
    repository: __MODEL_IMAGE_REPOSITORY__
    tag: __MODEL_IMAGE_TAG__
  name: model
  probes:
    liveness:
      initialDelaySeconds: 10
      path: /health
      periodSeconds: 10
      port: 5000
    readiness:
      initialDelaySeconds: 5
      path: /health
      periodSeconds: 5
      port: 5000
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    port: 5000
    targetPort: 5000
    type: ClusterIP
